global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Logging;
global using NorthWind.Exceptions.Entities.ExceptionHandlers;
global using NorthWind.Exceptions.Entities.Exceptions;
global using NorthWind.Exceptions.Entities.Extensions;
global using NorthWind.Exceptions.Entities.Resources;
global using NorthWind.Validation.Entities.ValueObjects;
global using System.Text.Json;
